# Generated by Django 3.0.6 on 2020-05-19 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feeditem',
            unique_together={('feed', 'title')},
        ),
    ]
