# Generated by Django 3.0.6 on 2020-05-22 21:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20200520_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeditem',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together={('user', 'url')},
        ),
    ]
