# Generated by Django 3.0.6 on 2020-05-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200522_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeditem',
            options={},
        ),
        migrations.RemoveField(
            model_name='feed',
            name='description',
        ),
    ]
